---
  - name: install php and php modules
    apt: name={{ item }}
         update_cache=yes
         state=latest
    with_items:
      - php
      - libapache2-mod-php
      - php-mysql
# tasks file for php
